export default Object.freeze({
  ILLNESS_GROUP: 'ILLNESS_GROUP',
  QUESTIONNAIRE_SCREEN: 'QUESTIONNAIRE SCREEN',
  HOME: 'HOME',
  RESULT_DETAIL: 'RESULT DETAIL',
  RESULT_LIST: 'RESULT LIST',
  ILLNESS_DETAIL: 'ILLNESS DETAIL',
  ONBOARDING: 'ONBOARDING',
  TEST_CONSENT_SCREEN: 'TEST_CONSENT_SCREEN',
  INFO_SCREEN: 'INFO_SCREEN',
});
